template-ui/channel-overrides/sikana/components/Card.vue, template-ui/src/components/Card.vue, template-ui/src/components/GridPage.vue, template-ui/src/store/index.js
https://phabricator.endlessm.com/T31668
=> Sikana improvements

template-ui/src/App.vue
If the URL has a topic ID passed in the query string, then redirect to
that topic in the custom presentation.
https://phabricator.endlessm.com/T31672
=> Template: Redirect to topic

template-ui/src/components/Card.vue, template-ui/src/components/CollapsibleCardGrid.vue, template-ui/src/components/GridPage.vue, template-ui/src/components/HeaderNavBarBrand.vue, template-ui/src/store/index.js
https://phabricator.endlessm.com/T31676
=> T31676 cards layout

template-ui/src/components/FilterContent.vue, template-ui/src/components/Header.vue, template-ui/src/store/index.js, template-ui/src/store/modules/filters.js, template-ui/src/views/Home.vue, template-ui/src/views/Section.vue
https://phabricator.endlessm.com/T31690
=> Filter Component

template-ui/src/store/index.js
https://phabricator.endlessm.com/T31676
=> Template: Don't default to high quality media

template-ui/src/components/Card.vue, template-ui/src/components/CollapsibleCardGrid.vue, template-ui/src/components/GridPage.vue, template-ui/src/components/HighResCard.vue, template-ui/src/components/LowResCard.vue, template-ui/src/components/RegularCard.vue, template-ui/src/components/mixins/cardMixin.js, template-ui/src/constants.js, template-ui/src/store/index.js
https://phabricator.endlessm.com/T31724
=> T31724 cards

template-ui/src/App.vue, template-ui/src/components/Header.vue, template-ui/src/components/HeaderOld.vue
https://phabricator.endlessm.com/T31716
=> T31716 header

template-ui/src/styles.scss
To Endless orange.
https://phabricator.endlessm.com/T31718
=> template: Set new default primary color

template-ui/src/components/FilterContent.vue, template-ui/src/store/modules/filters.js
https://phabricator.endlessm.com/T31717
=> template: Polish filter implementation

template-ui/channel-overrides/healthy-living/options.json, template-ui/src/App.vue, template-ui/src/components/CardBody.vue, template-ui/src/components/Carousel.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/components/FilterContent.vue, template-ui/src/components/Header.vue, template-ui/src/components/HeaderOld.vue, template-ui/src/components/HighResCard.vue, template-ui/src/components/LowResCard.vue, template-ui/src/components/MainSections.vue, template-ui/src/components/RegularCard.vue, template-ui/src/components/SectionTitle.vue, template-ui/src/components/mixins/cardMixin.js, template-ui/src/store/index.js, template-ui/src/styles.scss, template-ui/src/views/Home.vue, template-ui/src/views/Section.vue
Note: to avoid a conflict this is on top of #46.
https://phabricator.endlessm.com/T31767
=> T31767 header

template-ui/src/components/CardBody.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/components/HighResCard.vue, template-ui/src/components/LowResCard.vue, template-ui/src/components/RegularCard.vue, template-ui/src/components/SectionTitle.vue, template-ui/src/components/mixins/cardMixin.js, template-ui/src/store/index.js
https://phabricator.endlessm.com/T31768
=> T31768 cards

template-ui/src/components/FilterContent.vue, template-ui/src/store/modules/filters.js, template-ui/src/utils.js
Don't show all filter options by default, so it's not possible to have
a filtering without results.
https://phabricator.endlessm.com/T31722
=> template: Show only possible options in filters

template-ui/src/components/CardGrid.vue, template-ui/src/components/CollapsibleCardGrid.vue, template-ui/src/components/HighResCard.vue, template-ui/src/components/LowResCard.vue, template-ui/src/components/PaginatedCardGrid.vue, template-ui/src/components/RegularCard.vue, template-ui/src/components/SlidableCardGrid.vue, template-ui/src/store/index.js, template-ui/src/views/Home.vue, template-ui/src/views/Section.vue
https://phabricator.endlessm.com/T31779
=> T31779 cards row

template-ui/src/store/modules/filters.js, template-ui/src/views/Home.vue
https://phabricator.endlessm.com/T31792
=> Add filter for tags

template-ui/src/components/ContentLink.vue, template-ui/src/components/MainSections.vue, template-ui/src/components/SectionTitle.vue, template-ui/src/store/index.js
https://phabricator.endlessm.com/T31802
=> T31802 topics page

template-ui/src/store/modules/filters.js
This feature wasn't requested, let's avoid implementing things just in
case.
https://phabricator.endlessm.com/T31792
=> Template: Revert exclude option from tags

template-ui/src/components/FilterContent.vue, template-ui/src/store/index.js, template-ui/src/store/modules/filters.js
https://phabricator.endlessm.com/T31799
=> T31799 structured tags

template-ui/src/components/CardBody.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/constants.js, template-ui/src/store/modules/filters.js, template-ui/src/utils.js
https://phabricator.endlessm.com/T31799
=> T31799 structured part2

template-ui/src/components/CardBody.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/components/EmptyResultsMessage.vue, template-ui/src/constants.js, template-ui/src/store/modules/filters.js, template-ui/src/views/Home.vue, template-ui/src/views/Section.vue
https://phabricator.endlessm.com/T31817
=> T31817 playthrough changes

template-ui/src/views/Section.vue
Bug added in cc9872e4 at the last minute.
https://phabricator.endlessm.com/T31817
=> template: Fix empty check in Section

template-ui/src/App.vue, template-ui/src/components/ContentImage.vue, template-ui/src/components/ContentLink.vue, template-ui/src/components/Header.vue, template-ui/src/components/MainSections.vue, template-ui/src/components/SectionTitle.vue, template-ui/src/router/index.js, template-ui/src/store/index.js, template-ui/src/views/Content.vue, template-ui/src/views/Home.vue, template-ui/src/views/Section.vue
https://phabricator.endlessm.com/T31800
https://phabricator.endlessm.com/T31800
=> T31806 navigation

template-ui/src/components/ContentImage.vue
https://phabricator.endlessm.com/T31800
=> template: Add play icon to detail page image

template-ui/src/App.vue, template-ui/src/views/Home.vue
https://phabricator.endlessm.com/T31869
=> template: Display main section buttons only in home view

template-ui/src/components/CardBody.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/store/modules/filters.js
https://phabricator.endlessm.com/T31813
=> T31813 card tags

README.md, pbskids-ui/.env.development, pbskids-ui/src/App.vue, template-ui/.env.development, template-ui/src/App.vue
https://phabricator.endlessm.com/T31880
=> T31880 mock nodes fix

template-ui/src/components/Breadcrumb.vue, template-ui/src/components/Header.vue, template-ui/src/store/index.js, template-ui/src/views/Content.vue
https://phabricator.endlessm.com/T31871
=> T31871 breadcrumb

template-ui/src/components/CardMediaType.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/components/HighResCard.vue, template-ui/src/components/LowResCard.vue, template-ui/src/components/RegularCard.vue
This new component shows an icon with the media type and if the content
is a vide it shows the duration information provided by the structured
tag "duration".
https://phabricator.endlessm.com/T31874
=> template: Add CardMediaType component

template-ui/src/components/CardMediaType.vue
Turn the b-badge into a b-button component and call the API to open
the lightbox on click.
https://phabricator.endlessm.com/T31935
=> Template: Click on card play button opens lightbox

template-ui/src/components/SlidableCardGrid.vue
- Set outline variant and chevron icons.
- Don't overlap the card.
https://phabricator.endlessm.com/T31964
=> Template: Improve the style of CardRow buttons

template-ui/src/components/Carousel.vue, template-ui/src/constants.js
- Use fade transitions.
- Change the interval to 10 seconds.
Also, move the constant to the constants module.
https://phabricator.endlessm.com/T31961
=> template: Improve carousel style

template-ui/src/components/FilterContent.vue
This patch clears the filter on mounted, to avoid to keep the same
filter when changing the section selected.
https://phabricator.endlessm.com/T31952
=> template: Clear the filter on mounted

template-ui/src/components/CardBody.vue, template-ui/src/components/CarouselCard.vue, template-ui/src/styles.scss
https://phabricator.endlessm.com/T31912
=> template: Use CardBody component on CarouselCard
